# Generated by Django 4.0 on 2023-05-17 20:45

import apps.helper.utilities
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.CharField(default=apps.helper.utilities.pkgen, max_length=8, primary_key=True, serialize=False)),
                ('name_category', models.CharField(max_length=255, unique=True)),
                ('description_category', models.TextField()),
                ('image_category', models.ImageField(upload_to='Category')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.CharField(default=apps.helper.utilities.pkgen, max_length=8, primary_key=True, serialize=False)),
                ('name_product', models.CharField(max_length=255)),
                ('price_product', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description_product', models.TextField()),
                ('stock_product', models.IntegerField()),
                ('image_product', models.ImageField(upload_to='Items/')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ('-created_at',),
            },
        ),
    ]
