# Generated by Django 4.0 on 2023-05-14 22:08

import apps.helper.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id_category',
            field=models.CharField(default=apps.helper.utilities.pkgen, max_length=8, primary_key=True, serialize=False),
        ),
    ]
