# Generated by Django 4.0 on 2023-05-14 23:07

import apps.helper.utilities
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_id_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_category',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.CharField(default=apps.helper.utilities.pkgen, max_length=8, primary_key=True, serialize=False)),
                ('name_product', models.CharField(max_length=255)),
                ('price_product', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description_product', models.TextField()),
                ('stock_product', models.IntegerField()),
                ('image_product', models.ImageField(upload_to='Items')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
