# Generated by Django 4.0 on 2023-05-20 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_dreceiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='dreceiver',
            new_name='receiver',
        ),
    ]
