# Generated by Django 4.0 on 2023-05-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_dreceiver_order_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receiver_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
