# Generated by Django 4.0 on 2023-05-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_receiver_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='receiver',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='receiver_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
