# Generated by Django 4.0 on 2023-05-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_paid_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
