# Generated by Django 4.0 on 2023-06-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_offer_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
