# Generated by Django 4.0 on 2023-06-02 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_offer_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='offer_start_date',
        ),
    ]
