# Generated by Django 4.0 on 2023-06-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_product_offer_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='receiver',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='receiver_address',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
