# Generated by Django 4.0 on 2023-06-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_rename_city_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='receiver_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
